### ISSUE TITLE
Multiple lines?

### ISSUE THREAD

**Issue by PizzaMC** [zedwick/BungeeChatFilter#14]
How can I add multiple lines for a message action?
I tried /n and it doesnt work.
I also tried adding multiple lines under "messages:" like this:
#Shortcut for website URL can use either /url or /website
    CreateCommand:
        regex: (/help)|(/ehelp)
        actions:
            message: 
                - '&f'
                - '&eFor help with payments or donation issues:'
                - '&bHIDDEN'
                - '&eTo report bugs found on the server:'
                - '&bHIDDEN'
                - '&eTo contact staff members on Teamspeak'
                - '&bHIDDEN'
                - '&eTo contact staff members on Discord'
                - '&bHIDDEN'
                - '&f'

**Comment by zedwick** [comment]
Sorry, there's not currently a way to add multiple lines. There should be! So hopefully we'll get this added soon :)

**Comment by zedwick** [comment]
I was mistaken when I said you could not add multiple lines. \n will not work if you surround your string with ' ', you must use " " instead.

As of version 1.7 you can also use a list to add multiple lines.
