### ISSUE TITLE
Something broke between 1.6.2 and 1.6.4

### ISSUE THREAD

**Issue by hankur** [zedwick/BungeeChatFilter#5]
It's me again.

I updated the plugin from 1.6.1 to 1.6.4 and most of the rules didn't work anymore. Some did, but most didn't and I'm not sure why. So I downgraded back to 1.6.2 without any changes to the config and it magically started working again.

**Comment by zedwick** [comment]
Please be more specific as to which rules work and which do not; providing your config file would be helpful.

**Comment by zedwick** [comment]
1.6.3 introduced a change where only monitored commands listed under the commands section of the config will be matched with rules, so any rules which match /commands will likely not work unless they have been listed properly in the config. I suspect this is your issue.

**Comment by hankur** [comment]
Sorry for the late reply. Yes, that was the issue, but I suspect I'm not the only one that had this problem. You should write a comment on the plugin page about this.

Edit: And by the way, the default config should include the "shop" command as well in the monitored commands list (there's double "hub").

**Comment by zedwick** [comment]
Aye, I did mention it in the update changelog I think. It's not the most elegant solution, I'm just not sure how to make it more intuitive.
