### ISSUE TITLE
Get original command/text in action.

### ISSUE THREAD

**Issue by leonfagan71** [zedwick/BungeeChatFilter#8]
I'd like to be able to get the original command/chat message text if it matches a rule.

Is it possible to get the original command/text and use it like::
ccommand: warn {player} Swearing  {originalText}.

Regards.

**Comment by zedwick** [comment]
This would be good, aswell as maybe {matchingText} to return just the string caught by the regex.

**Comment by leonfagan71** [comment]
This is located in Rule.java line 80, just add another replace with {message} 
I've added .replace( "{message}", message ) into a request.
